# Generated by Django 6.0 on 2026-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_alter_exhibition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
