# Generated by Django 5.2.1 on 2026-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.CharField(choices=[('couple', 'Couple Pottery Dates'), ('birthday', 'Birthday Celebrations'), ('farm', 'Farm & Garden Mini Parties'), ('studio', 'Studio-based Experiences')], max_length=20)),
                ('date', models.DateField()),
                ('participants', models.PositiveIntegerField()),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
