# Generated by Django 5.2.1 on 2026-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
